/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataEngine.Array;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ilham
 */
public class Edit extends javax.swing.JFrame {

    private final int COL_NIM = 0;
    private final int COL_NAMA = 1;
    private final int COL_JURUSAN = 2;
    private final int COL_JK = 3;
    private final int COL_PENYAKIT = 4;
    private final int COL_KAMAR = 5;

    private String where;
    private int by;

    private String NIM;
    private String Nama;
    private char JK;
    private String Jurusan;
    private String Penyakit;
    private String Kamar ;
    private String[] searchRes;

    /**
     * Creates new form Add
     */
    public Edit() {
        initComponents();
        setEnable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        optBy = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        txtNIM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtPenyakit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboJK = new javax.swing.JComboBox<>();
        jJurusan = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jKamar = new javax.swing.JComboBox();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtWhere = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDIT MAHASISWA");
        setResizable(false);

        jPanel1.setLayout(null);

        optBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM", "Nama" }));
        optBy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                optByKeyPressed(evt);
            }
        });
        jPanel1.add(optBy);
        optBy.setBounds(250, 10, 75, 29);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("NIM :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 60, 26, 14);

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel1.add(btnFind);
        btnFind.setBounds(330, 10, 53, 30);

        txtNIM.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtNIM);
        txtNIM.setBounds(100, 60, 210, 20);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("NAMA :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 90, 36, 14);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("JURUSAN :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 120, 53, 14);

        txtNama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtNama);
        txtNama.setBounds(100, 90, 210, 20);
        jPanel1.add(txtPenyakit);
        txtPenyakit.setBounds(100, 150, 210, 20);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("JENIS KELAMIN :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 180, 81, 14);

        comboJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        jPanel1.add(comboJK);
        comboJK.setBounds(100, 180, 127, 20);

        jJurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pendidikan Agama Islam", "Pendidikan Ilmu Pengetahuan Sosial", "Pendidikan Bahasa Arab", "Pendidikan Islam Anak Usia Dini", "Manajemen Pendidikan Islam", "Tadris Bahasa Inggris", "Tadris Matematika", "al-Ahwal al-Syakhshiyyah", "Hukum Bisnis Syaria'ah", "Hukum Tata Negara", "Al-qur'an dan Ilmu Tafsir", "Bahasa dan Sastra Arab", "Sastra Inggris", "Psikologi", "Managemen", "Akuntansi", "Perbankan Syariah", "Matematika", "Biologi", "Fisika", "Kimia", "Teknik Informatika", "Teknik Arsitektur", "Perpustakaan dan Ilmu informasi", "Farmasi", "Pendidikan Dokter", "Profesi Dokter", " ", " ", " " }));
        jJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJurusanActionPerformed(evt);
            }
        });
        jPanel1.add(jJurusan);
        jJurusan.setBounds(100, 120, 196, 20);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("PENYAKIT :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 150, 61, 14);

        jKamar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 A", "1 B", "1 C", "2 A", "2 B", "2 C", "3 A", "3 B", "3 C", "4 A", "4 B", "4 C", "5 A", "5 B", "5 C", "6 A", "6 B", "6 C", "7 A", "7 B", "7 C", "8 A", "8 B", "8 C", "9 A", "9 B", "9 C", "10 A", "10 B", "10 C", "11 A", "11 B", "11 C", "12 A", "12 B", "12 C", "13 A", "13 B", "13 C", "BEDAH 1 A", "BEDAH 1 B", "BEDAH 1 C", "BEDAH 2 A", "BEDAH 2 B", "BEDAH 2 C", "ISOLASI 1", "ISOLASI 2 ", "ISOLASI 3", "ISOLASI 4" }));
        jKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKamarActionPerformed(evt);
            }
        });
        jPanel1.add(jKamar);
        jKamar.setBounds(100, 210, 77, 20);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(50, 260, 121, 39);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);
        btnCancel.setBounds(210, 260, 121, 39);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("KAMAR :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 210, 42, 14);

        txtWhere.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWhereKeyPressed(evt);
            }
        });
        jPanel1.add(txtWhere);
        txtWhere.setBounds(10, 10, 235, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateVar() {
        this.where = txtWhere.getText().trim().toLowerCase();
        this.by = optBy.getSelectedIndex();
    }

    /**
     * FALIDASI STRING KE INTEGER
     *
     * @param STRING TEXT YANG AKAN DIVALIDASI
     * @return BOOLEAN HASIL
     */
    private boolean checkInt(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException e) {
            System.out.println("NOT NUMBER!");
        }
        return false;
    }
   
   
    /**
     * TOMBOL UPDATE DI PENCET
     * @param evt 
     */
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //cek kosong

        if ("".equals(txtNIM.getText()) || "".equals(txtNama.getText()) || "".equals(jJurusan.getSelectedItem())
                || "".equals(txtPenyakit.getText())) {
            JOptionPane.showMessageDialog(null, "Semua form harus diisi!");
            return;
        }
        //cek input salah
        if (!checkInt(txtNIM.getText())) {
            JOptionPane.showMessageDialog(null, "Form NIM harus diisi angka!");
            return;
        }


        this.NIM = txtNIM.getText().trim();

        if (!MainUI.empty) {
            //pencarian
            //jika ada nim sama
            String[] res = MainUI.db.find(0, NIM);
            if (res != null) {
                if (!res[COL_NIM].equals(searchRes[COL_NIM])) {
                    JOptionPane.showMessageDialog(null, "NIM sudah ada!");
                    return;
                }
            }
        }

        this.Jurusan = jJurusan.getSelectedItem().toString().trim().toUpperCase();
        txtNIM.setText("");
        jJurusan.setSelectedItem("");
        this.Nama = txtNama.getText().trim().toUpperCase();
        txtNama.setText("");
        this.Penyakit = txtPenyakit.getText().trim().toUpperCase();
        txtPenyakit.setText("");
        this.JK = comboJK.getSelectedItem().toString().charAt(0);
        this.Kamar = jKamar.getSelectedItem().toString().trim().toUpperCase();
       
      

        MainUI.db.delete(searchRes[COL_NIM]);
        MainUI.db.insert(NIM, Nama, JK, Jurusan, Penyakit, Kamar);
        MainUI.saved = false;
        System.out.println("data updated");
        JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        resetForm();
        setEnable(false);
    }//GEN-LAST:event_btnUpdateActionPerformed
    /**
     * SET NILAI FORM BERDASARKAN HASIL CARI
     */
    public void setForm() {
        txtNIM.setText(searchRes[COL_NIM]);
        txtNama.setText(searchRes[COL_NAMA]);
        txtPenyakit.setText(searchRes[COL_PENYAKIT]);
        jJurusan.setSelectedItem(searchRes[COL_JURUSAN]);
        jKamar.setSelectedItem(searchRes[COL_KAMAR]);       
        //jk setter
        JK = searchRes[COL_JK].charAt(0);
        if (JK == 'L') {
            comboJK.setSelectedIndex(0);
        } else {
            comboJK.setSelectedIndex(1);
        }

    }
    /**
     * KOSONGIN FORM
     */
    public void resetForm() {
        txtWhere.setText("");
    }
    /**
     * HIDUP/MATIKAN FORM
     * @param cond TRUE/FALSE
     */
    public void setEnable(boolean cond) {
        if (cond) {
            txtNIM.setEnabled(true);
            txtNama.setEnabled(true);
            jJurusan.setEnabled(true);
            txtPenyakit.setEnabled(true);
            jKamar.setEnabled(true);
            comboJK.setEnabled(true);
            btnUpdate.setEnabled(true);
        } else {
            txtNIM.setEnabled(false);
            txtNama.setEnabled(false);
            jJurusan.setEnabled(false);
            txtPenyakit.setEnabled(false);
            jKamar.setEnabled(false);
            comboJK.setEnabled(false);
            btnUpdate.setEnabled(false);
        }
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed
    /**
     * find mahasiswa
     * @param evt 
     */
    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        updateVar();
        if (!where.equals("")) {
            searchRes = MainUI.db.find(by, where);
            if (searchRes == null) {
                JOptionPane.showMessageDialog(null, "Kata kunci tidak ditemukan!");
                return;
            }
        } else {
            return;
        }
        setEnable(true);
        setForm();
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtWhereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWhereKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnFindActionPerformed(null);
        }
    }//GEN-LAST:event_txtWhereKeyPressed

    private void optByKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optByKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnFindActionPerformed(null);
        }
    }//GEN-LAST:event_optByKeyPressed

    private void jJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJurusanActionPerformed

    private void jKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboJK;
    private javax.swing.JComboBox jJurusan;
    private javax.swing.JComboBox jKamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> optBy;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPenyakit;
    private javax.swing.JTextField txtWhere;
    // End of variables declaration//GEN-END:variables
}
